### ISSUE TITLE
Instantiating multiparty.Form() throws "TypeError: Object #<Object> has no method 'on'" with node > 0.8

### ISSUE THREAD

**Issue by lxe** [andrewrk/node-multiparty#129]
... or "`TypeError: self.on is not a function`" depending on the node version.

```
~/test-multiparty$ node -v
v0.10.32
~/test-multiparty$ node
> require('multiparty').Form()
TypeError: Object #<Object> has no method 'on'
    at Object.Form (/Users/aleksey/test-multiparty/node_modules/multiparty/index.js:74:8)
    at repl:1:24
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
    at ReadStream.emit (events.js:98:17)
```

Looks like multiparty does not inherit `EventEmitter`, making `.on()` unavailable. This is happening here:

https://github.com/andrewrk/node-multiparty/blob/master/index.js#L74

It was introduced in here:

https://github.com/andrewrk/node-multiparty/commit/9cbf9f423bf625ee755b920513455772684298e2

I'm guessing the node version back then was 0.8, and `stream.Writable` has eventEmitter methods.

**Comment by dougwilson** [comment]
Hi! This module does not support Node.js 0.8 in any way, mainly because streams work very different between 0.8 and 0.10 and this module only works with steams2+ (0.10 and up). You can see we declared the required version of Node.js in our package.json file: https://github.com/andrewrk/node-multiparty/blob/master/package.json#L30 and `npm` should have provided a warning on install: `npm WARN engine multiparty@4.1.2: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.28","npm":"1.4.28"})`

**Comment by dougwilson** [comment]
Oops, sorry, I completely mis-read your issue, thinking you said 0.8, not "> 0.8". Your issue is that you are missing the `new` keyword. `require('multiparty').Form()` is invalid. You have to run `var multiparty = require('multiparty'); new multiparty.Form()`. You can find more information in our README :)

**Comment by lxe** [comment]
>  Your issue is that you are missing the new keyword. require('multiparty').Form() is invalid.

@dougwilson thank you for catching this. I must've had a looong day...

**Comment by dougwilson** [comment]
haha, yea, we've all been there :)
